name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Discord Webhook Notify
      uses: rjstone/discord-webhook-notify@v1.0.1
      with:
        # Discord webhook URL. Should be stored in a secret and inserted as a context expression.
        webhookUrl: {{ secrets.discord }}
        # Severity level - info, warn, or error
        severity: info # optional, default is error
        # Embed notification message. Use context expressions and environment variables to provide information. Default provides branch and user info.
        #description: Newly pushed code # optional
        # Additional text after the notification message in case you want to retain the default message.
        #details: # optional
        # Footer for the embed. Defaults to severity.
        #footer: # optional
        # Text to be sent as normal text above the embed. Use context expressions and environment variables to provide information.
        text: "{{ head_commit.message | truncate(128) }} {{ head_commit.id[0:7] }}" # optional
        # Username to display in discord.
        username: GITHUB BOT # optional
        # Notification color in the form poundsign rrggbb (hex). Default determined by severity.
        #color: # optional
        # URL to png of discord avatar to use. Default is the GitHub monochrome mark cat logo.
        avatarUrl: https://storage.ihvn.dev/icons/apps/ioshaven.jpg # optional


    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
